name: GVC
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11.3
  - numpy=1.26.4
  - scipy=1.15.2
  - matplotlib=3.10.0
  - scikit-learn=1.6.1
  - pandas
  - tqdm
  - jupyterlab

  - pip

  - pip:
    # Add PyTorch with CUDA support via find-links
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch==2.5.1+cu118
    - torchvision